### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by matthughes** [jwilder/docker-squash#19]
Got the following when trying to squash library/centos:7.  This is using Docker 1.5 on ubuntu and 0.0.11.

```
docker save library/centos:7 | sudo ./dockerbin/docker-squash -t squashed -verbose | docker load
Loading export from STDIN using /tmp/docker-squash897833692 for tempdir
Loaded image w/ 3 layers
  -  library/centos (1 tags)
Extracting layers...
  -  /tmp/docker-squash897833692/511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158/layer.tar
  -  /tmp/docker-squash897833692/5b12ef8fd57065237a6833039acc0e7f68e363c15d8abb5cacce7143a1f7de8a/layer.tar
  -  /tmp/docker-squash897833692/dade6cb4530a852b83bc34f6f3904a10879632947c01f1ae0447ff9dbb37e12b/layer.tar
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x50 pc=0x4042a2]

goroutine 16 [running]:
runtime.panic(0x5842e0, 0x693cf3)
    /usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
main.(*Export).InsertLayer(0xc2080423c0, 0xc20800e400, 0x40, 0xc208095d98, 0x0, 0x0)
    /home/jwilder/go/src/github.com/jwilder/docker-squash/export.go:393 +0x7d2
main.main()
    /home/jwilder/go/src/github.com/jwilder/docker-squash/main.go:130 +0xd37

goroutine 19 [finalizer wait]:
runtime.park(0x41ea00, 0x697d08, 0x696829)
    /usr/local/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x697d08, 0x696829)
    /usr/local/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
    /usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
    /usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 20 [syscall]:
os/signal.loop()
    /usr/local/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
    /usr/local/go/src/pkg/os/signal/signal_unix.go:27 +0x32

goroutine 21 [chan receive]:
main.shutdown(0xc208042380, 0x1b)
    /home/jwilder/go/src/github.com/jwilder/docker-squash/main.go:22 +0x60
created by main.main
    /home/jwilder/go/src/github.com/jwilder/docker-squash/main.go:73 +0x6f2
FATA[0006] Error: EOF

```

**Comment by ppLorins** [comment]
I encounter the same problem .
