### ISSUE TITLE
throws null pointer exception

### ISSUE THREAD

**Issue by senior7515** [jwilder/docker-squash#30]
# First: Listing docker images.

```
root@agallego:/tmp/alex# docker images
REPOSITORY                    TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
concord/client_devbox         latest              8d2b61676ad1        23 minutes ago      2.401 GB
concord/light_client_devbox   latest              7bbcba9980f2        25 minutes ago      2.401 GB
<none>                        <none>              702ee68f9a1f        40 minutes ago      2.476 GB

```
### When trying to squash, with either `-from` , no -from argument or a hash id it breaks like this.

```

root@agallego:/tmp/alex# docker save concord/client_devbox | docker-squash -from 8d2b61676ad1 -t concord/client_devbox_3 | docker load 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x50 pc=0x404c22]

goroutine 1 [running]:
main.(*Export).InsertLayer(0xc20801e340, 0xc2080429c0, 0x40, 0xc208038240, 0x0, 0x0)
        /Users/jason/go/src/github.com/jwilder/docker-squash/export.go:395 +0xa72
main.main()
        /Users/jason/go/src/github.com/jwilder/docker-squash/main.go:130 +0xee7

goroutine 5 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 6 [chan receive]:
main.shutdown(0xc20803c540, 0x25)
        /Users/jason/go/src/github.com/jwilder/docker-squash/main.go:22 +0x67
created by main.main
        /Users/jason/go/src/github.com/jwilder/docker-squash/main.go:73 +0x7d8
Error response from daemon: EOF
```

**Comment by jwilder** [comment]
Can you run `docker version` and post the output?

**Comment by senior7515** [comment]
```
$ docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
```
