### ISSUE TITLE
Bug:  panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ppLorins** [jwilder/docker-squash#39]
reproduce:
1. docker save -o compressed.tar init:compressed
2. sudo docker-squash -i ~/compressed.tar -o squashed.tar

images history:

```
arthurwangs-MacBook-Pro:docker-squash arthur$ docker history init:compressed
IMAGE               CREATED             CREATED BY          SIZE                COMMENT
1d345e8af171        2 days ago                              953.6 MB            Imported from -
```

docker-squash must the newest version since I just download it at 3 days ago.

docker version:

```
arthurwangs-MacBook-Pro:docker-squash arthur$ docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by ppLorins** [comment]
This won't reproduce after I use a full-history image, like this:
```
arthurwangs-MacBook-Pro:docker-squash arthur$ docker history init:m3
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
8610f009ce79        2 days ago          /bin/bash                                       516 MB              
e3404949f915        2 days ago          /bin/bash                                       330.9 MB            
67db4bbfee71        2 days ago          /bin/bash                                       173.6 MB            
0990f400a520        3 days ago          /bin/bash                                       11.91 kB            
997b21c58b46        3 days ago          /bin/bash                                       11.98 kB            
fc250b25ea36        3 days ago          /bin/bash                                       11.6 kB             
2b9b2bff965b        3 days ago          /bin/bash                                       10.31 kB            
659d8bd6f08c        3 days ago          /bin/bash                                       64.01 MB            
83e3ca3e8fb1        3 days ago          /bin/bash                                       176.5 MB            got vim and gcc
f00b46a61daa        3 days ago          /bin/sh -c python /my/test.py                   79.33 MB            
2762c352b7ac        3 days ago          /bin/sh -c #(nop) CMD ["/bin/sh" "-c" "python   0 B                 
c203f50fbcf6        3 days ago          /bin/sh -c #(nop) COPY file:c7b1b95a8769226d0   44 B                
5e9802b25df9        3 days ago          /bin/sh -c #(nop) ENTRYPOINT &{["/bin/sh" "-c   0 B                 
1871d7cba24b        4 days ago          /bin/sh -c yum install python                   64.17 MB            
ce20c473cd8a        4 weeks ago         /bin/sh -c #(nop) CMD ["/bin/bash"]             0 B                 
4234bfdd88f8        4 weeks ago         /bin/sh -c #(nop) LABEL License=GPLv2           0 B                 
812e9d9d677f        4 weeks ago         /bin/sh -c #(nop) LABEL Vendor=CentOS           0 B                 
168a69b62202        4 weeks ago         /bin/sh -c #(nop) ADD file:125fe45519717bec39   172.3 MB            
47d44cb6f252        9 weeks ago         /bin/sh -c #(nop) MAINTAINER The CentOS Proje   0 B 
```



confusing ...

**Comment by nuklea** [comment]
Have same problem:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x50 pc=0x4054d4]

goroutine 1 [running]:
main.(*Export).InsertLayer(0xc8200143e0, 0xc82000b900, 0x40, 0xc820331d38, 0x0, 0x0)
        /Users/jason/go/src/github.com/jwilder/docker-squash/export.go:395 +0xab4
main.main()
        /Users/jason/go/src/github.com/jwilder/docker-squash/main.go:130 +0xf3f

goroutine 5 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 6 [select, locked to thread]:
runtime.gopark(0x64a880, 0xc820024728, 0x5f69c8, 0x6, 0x438918, 0x2)
        /usr/local/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc820024728, 0x0, 0x18)
        /usr/local/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc820024728)
        /usr/local/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
        /usr/local/go/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 7 [chan receive]:
main.shutdown(0xc8200143a0, 0x1b)
        /Users/jason/go/src/github.com/jwilder/docker-squash/main.go:22 +0x7d
created by main.main
        /Users/jason/go/src/github.com/jwilder/docker-squash/main.go:73 +0x813
invalid argument
```

**Comment by fabiomartinelli** [comment]
same here

**Comment by falco467** [comment]
Same Problem with current version

**Comment by mixxen** [comment]
Also having a nil pointer error. Different line number:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x402438]

goroutine 1 [running]:
main.LoadExport(0x7ffdd2b6085a, 0x9, 0xc820010420, 0x1b, 0xc82009e010, 0x0, 0x0)
	/Users/jason/go/src/github.com/jwilder/docker-squash/export.go:183 +0x11e8
main.main()
	/Users/jason/go/src/github.com/jwilder/docker-squash/main.go:76 +0x84a

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 17 [select, locked to thread]:
runtime.gopark(0x64a880, 0xc820026728, 0x5f69c8, 0x6, 0x438918, 0x2)
	/usr/local/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc820026728, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc820026728)
	/usr/local/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 18 [chan receive]:
main.shutdown(0xc820010420, 0x1b)
	/Users/jason/go/src/github.com/jwilder/docker-squash/main.go:22 +0x7d
created by main.main
	/Users/jason/go/src/github.com/jwilder/docker-squash/main.go:73 +0x813
```

**Comment by jmarronm** [comment]
+1
Exactly same error than previous comment using v0.2.0

**Comment by Guptajakala** [comment]
Same problem here, not fixed yet?

```
Loading export from STDIN using /tmp/docker-squash011535009 for tempdir
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x402438]

goroutine 1 [running]:
main.LoadExport(0x0, 0x0, 0xc8200163c0, 0x1b, 0xc82009c010, 0x0, 0x0)
	/Users/jason/go/src/github.com/jwilder/docker-squash/export.go:183 +0x11e8
main.main()
	/Users/jason/go/src/github.com/jwilder/docker-squash/main.go:76 +0x84a

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 17 [select, locked to thread]:
runtime.gopark(0x64a880, 0xc820024728, 0x5f69c8, 0x6, 0x438918, 0x2)
	/usr/local/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc820024728, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc820024728)
	/usr/local/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 18 [chan receive]:
main.shutdown(0xc8200163c0, 0x1b)
	/Users/jason/go/src/github.com/jwilder/docker-squash/main.go:22 +0x7d
created by main.main
	/Users/jason/go/src/github.com/jwilder/docker-squash/main.go:73 +0x813
open /var/lib/docker/tmp/docker-import-272900474/repositories: no such file or directory
```

**Comment by AVANZHAOYONG** [comment]
same here！
