### ISSUE TITLE
Squash dies with stacktrace

### ISSUE THREAD

**Issue by mcameron** [jwilder/docker-squash#77]
Squash fails when running:
`docker save myimage:latest | sudo docker-squash -t squash -verbose | docker load`

Here's the error: 
```
Loading export from STDIN using /tmp/docker-squash459387669 for tempdir
Loaded image w/ 10 layers
  -  myimage (1 tags)
Extracting layers...
  -  /tmp/docker-squash459387669/e32fb7fa5f6f0a1f2d20d6a04c172acf2456266f3caa10e57add58873e764588/layer.tar
  -  /tmp/docker-squash459387669/145d68c584b4586c93a0227ce2477af5e8b56f71a7f1ab4b8e091bb6b41d77bd/layer.tar
  -  /tmp/docker-squash459387669/61ce2e3c873804b1f7974d14fa0f492388efac875fa5429c06565d1ccea3058d/layer.tar
  -  /tmp/docker-squash459387669/8502b308d633cf010bdf57983dce7f0dbb9f159f0576a00c0ad65cd60aef216a/layer.tar
  -  /tmp/docker-squash459387669/8acb75847d8140db11731f6513c5bb39665159a331ff30d5bbda1592bc1c2a1a/layer.tar
  -  /tmp/docker-squash459387669/c081b945efe15a16ab0b0cc3d46134bcfdd2ff59cf8723eb857f1246ef69784c/layer.tar
  -  /tmp/docker-squash459387669/229b746f662f28126611b8739f22119f0e56944cc46633558709c4a8fbfd5b35/layer.tar
  -  /tmp/docker-squash459387669/8ca22a79446f5edebe06fbfffb1f5fe7b62fb5d2f573e63d0700363e9ae6822a/layer.tar
  -  /tmp/docker-squash459387669/bb080df7fdeb161a691eb13ca65e658cdbccc96f8c5c214c74093b97adb7ef0e/layer.tar
  -  /tmp/docker-squash459387669/ca244bc7885cfb03becc81b120a8a4e1bb34532b89fcd3cf70428db81cd54157/layer.tar
Inserted new layer 878f0bb2ea41 after 229b746f662f
  -  229b746f662f
  -> 878f0bb2ea41 /bin/sh -c #(squash) from 229b746f662f
  -  145d68c584b4
  -  8acb75847d81
  -  61ce2e3c8738
  -  8ca22a79446f
  -  8502b308d633
  -  c081b945efe1
  -  bb080df7fdeb
  -  e32fb7fa5f6f
  -  ca244bc7885c /bin/sh -c #(nop)  ENTRYPOINT ["/start.sh"]
Squashing from 878f0bb2ea41 into 878f0bb2ea41
  -  Deleting whiteouts for layer 145d68c584b4
fatal error: still in list

runtime stack:
runtime.throw(0x1fb0f0, 0xd)
	/usr/local/go/src/runtime/panic.go:527 +0x90
runtime.mHeap_AllocSpanLocked(0x2f7020, 0x4, 0x0)
	/usr/local/go/src/runtime/mheap.go:590 +0x40c
runtime.mHeap_AllocStack(0x2f7020, 0x4, 0x1)
	/usr/local/go/src/runtime/mheap.go:502 +0x77
runtime.stackpoolalloc(0x313802, 0xc81ffd87e7)
	/usr/local/go/src/runtime/stack1.go:71 +0x5e
runtime.stackcacherefill(0x34d4b8, 0x2)
	/usr/local/go/src/runtime/stack1.go:149 +0x59
runtime.stackalloc(0xc800002000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/stack1.go:248 +0x1b0
runtime.malg.func1()
	/usr/local/go/src/runtime/proc1.go:2192 +0x2b
runtime.systemstack(0xc82009be60)
	/usr/local/go/src/runtime/asm_amd64.s:278 +0xab
runtime.malg(0xc800002000, 0x246268)
	/usr/local/go/src/runtime/proc1.go:2193 +0x73
runtime.allocm(0x0, 0x246268, 0x3d0aa)
	/usr/local/go/src/runtime/proc1.go:881 +0xb5
runtime.newm(0x246268, 0x0)
	/usr/local/go/src/runtime/proc1.go:1091 +0x2f
runtime.startTheWorldWithSema()
	/usr/local/go/src/runtime/proc1.go:664 +0x1fc
runtime.gc.func1()
	/usr/local/go/src/runtime/mgc.go:992 +0x95
runtime.systemstack(0xc82001c000)
	/usr/local/go/src/runtime/asm_amd64.s:262 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc1.go:674

goroutine 28 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc82021fc98 sp=0xc82021fc90
runtime.gc(0x0)
	/usr/local/go/src/runtime/mgc.go:1006 +0x1db fp=0xc82021ff90 sp=0xc82021fc98
runtime.backgroundgc()
	/usr/local/go/src/runtime/mgc.go:897 +0x3d fp=0xc82021ffc0 sp=0xc82021ff90
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82021ffc8 sp=0xc82021ffc0
created by runtime.startGC
	/usr/local/go/src/runtime/mgc.go:870 +0x186

goroutine 1 [running]:
	goroutine running on other thread; stack unavailable

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 6 [select, locked to thread]:
runtime.gopark(0x246300, 0xc82002e728, 0x1f36a8, 0x6, 0x39518, 0x2)
	/usr/local/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc82002e728, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc82002e728)
	/usr/local/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:227 +0x323
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 7 [chan receive]:
main.shutdown(0xc820010400, 0x1b)
	/Users/jason/go/src/github.com/jwilder/docker-squash/main.go:22 +0x7d
created by main.main
	/Users/jason/go/src/github.com/jwilder/docker-squash/main.go:73 +0x813
open /var/lib/docker/tmp/docker-import-892558389/repositories: no such file or directory
```

**Comment by meambobbo** [comment]
I am having the same issue as above. Any known fix/workaround?
