### ISSUE TITLE
404 Client Error: Not Found("open /scratch/docker-data/tmp/docker-import-764157190/repo/boot/json: no such file or directory")

### ISSUE THREAD

**Issue by leonfranzen** [jwilder/docker-squash#84]
I'm squashing a large 13 GB image down to around 8.  The process seems to succeed but in the end it fails with the below exception.  It happens when squashing to a file or directly to the local repository.  In the former case, the file does get written to disk but I need to directly write to the registry.  The reason for this requirement is also strange.  If I write the tar image and then import it, it is larger than the unsquashed image.

2019-03-19 14:00:02,639 root         INFO     Squashing finished!
2019-03-19 14:00:02,829 root         DEBUG    Reading JSON metadata file '/scratch/tmp/old/5cec968d5b037cc117f6b0dad73a92483a837decfb41a87b1b476097d6862791/json'...
2019-03-19 14:00:02,830 root         DEBUG    Removing from disk already squashed layers...
2019-03-19 14:00:04,589 root         INFO     Original image size: 12725.23 MB
2019-03-19 14:00:04,589 root         INFO     Squashed image size: 8663.02 MB
2019-03-19 14:00:04,589 root         INFO     Image size decreased by 31.92 %
2019-03-19 14:00:04,589 root         INFO     New squashed image ID is c2c473cb41517738d3a343b38b87af4e3bb677fd5ebb29a85061918487cca1d1
2019-03-19 14:00:04,590 root         DEBUG    Generating tar archive for the squashed image...
2019-03-19 14:00:41,381 root         DEBUG    Archive generated
2019-03-19 14:00:41,381 root         DEBUG    Loading squashed image...
2019-03-19 14:02:09,035 urllib3.connectionpool DEBUG    http://localhost:None "POST /v1.21/images/load HTTP/1.1" 404 96
2019-03-19 14:02:09,036 root         DEBUG    Cleaning up /scratch/tmp temporary directory
2019-03-19 14:02:10,643 root         ERROR    404 Client Error: Not Found ("open /scratch/docker-data/tmp/docker-import-764157190/repo/boot/json: no such file or directory")
Traceback (most recent call last):
  File "/root/.local/lib/python2.7/site-packages/docker_squash/cli.py", line 87, in run
    from_layer=args.from_layer, tag=args.tag, output_path=args.output_path, tmp_dir=args.tmp_dir, development=args.development, cleanup=args.cleanup).run()
  File "/root/.local/lib/python2.7/site-packages/docker_squash/squash.py", line 59, in run
    return self.squash(image)
  File "/root/.local/lib/python2.7/site-packages/docker_squash/squash.py", line 92, in squash
    image.load_squashed_image()
  File "/root/.local/lib/python2.7/site-packages/docker_squash/image.py", line 254, in load_squashed_image
    self._load_image(self.new_image_dir)
  File "/root/.local/lib/python2.7/site-packages/docker_squash/image.py", line 299, in _load_image
    self.docker.load_image(f)
  File "/root/.local/lib/python2.7/site-packages/docker/api/image.py", line 302, in load_image
    self._raise_for_status(res)
  File "/root/.local/lib/python2.7/site-packages/docker/api/client.py", line 258, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/root/.local/lib/python2.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
NotFound: 404 Client Error: Not Found ("open /scratch/docker-data/tmp/docker-import-764157190/repo/boot/json: no such file or directory")
2019-03-19 14:02:10,678 root         ERROR    Execution failed, consult logs above. If you think this is our fault, please file an issue: https://github.com/goldmann/docker-squash/issues, thanks!

**Comment by zot** [comment]
This works for me without using docker-squash:

1. Make a container that changes the image as in the normal docker-squash instructions
2. use `docker export CONTAINER-ID | docker import - REPOSITORY:TAG` to produce the squashed image

As far as I can tell, this produces an image similar to what docker-squash would produce.
