### ISSUE TITLE
Squash dies with fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by pomo-mondreganto** [jwilder/docker-squash#85]
I've saved a modified ubuntu image and try to squash it using the following command: 

```
sudo PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH" ~/Downloads/docker-squash -t squashed -from root -verbose -i ubuntu.tar -o result.tar
```

I'm using macOS 10.14 with gnu-tar installed with homebrew. 

Here's the output fo unsuccessful execution: 

```
Loading export from ubuntu.tar using /tmp/docker-squash892084052 for tempdir
Loaded image w/ 25 layers
Extracting layers...
  -  /tmp/docker-squash892084052/7b282b939ce9699d29e2f9f32720281da29f7b6c1fc6f4d0f323e94764365697/layer.tar
  -  /tmp/docker-squash892084052/870d3f402f75021060706f2cbe98030c77db022fd0435e78ba32c9318ce9001c/layer.tar
  -  /tmp/docker-squash892084052/b4aaa2a9b1c803b2d5e2be58eb77fc258749f3e67bfd9b06677e0c4ec551c580/layer.tar
  -  /tmp/docker-squash892084052/02967406f25da0ade833dc56e1111c4602b0596069772340a53087b4a59bb611/layer.tar
  -  /tmp/docker-squash892084052/648f99dd0ed7a70abffe61a9e6cc941fc207b8633b300c4ffb818147b859f6c8/layer.tar
  -  /tmp/docker-squash892084052/66a8e762bd6f0f0c5971f79ed664c1c82d1b46053a617e73703f018e88ef980f/layer.tar
  -  /tmp/docker-squash892084052/5f0a9548e36222e7269ed28e806dd754c55cc4a103763e9bd5d24078619a7a5b/layer.tar
  -  /tmp/docker-squash892084052/a3c77c9bff4b76ebb10c03fdb4412507c07e2229429c322c7e2c505c4391602f/layer.tar
  -  /tmp/docker-squash892084052/b2b5c564bc383fc55dd99ec6e659739e64be2149c8a0a25cf6ea3c379b93dc09/layer.tar
  -  /tmp/docker-squash892084052/b40fae1c32824b69017ffeb2ddb45afaeddec0ef5e0f5b51cc8ecffa1d8c54aa/layer.tar
  -  /tmp/docker-squash892084052/09857f32078e8750437fc8f9ca62f0b59b01ed0a4b5ba9f946756aeb772a8c10/layer.tar
  -  /tmp/docker-squash892084052/562e427f3c175776f57cc64b4cd6a14b73b35e90b7965146912c5b8a10242c72/layer.tar
  -  /tmp/docker-squash892084052/5a22554e2f566fc5877473568249591607395faddf57a4d519a061ce3b59ecbc/layer.tar
  -  /tmp/docker-squash892084052/7982da6edf5b02c784cbafe8f151b8c8bbb88c51a84ec9319f0ecad587b75c92/layer.tar
  -  /tmp/docker-squash892084052/cd2ccadceb077ad27666f0ad66f7e181aaf377608590c9d236452b27a4675fe0/layer.tar
  -  /tmp/docker-squash892084052/0717c411df0c6544c10af52f348bf6a259f4b7e52c4781cc6f461a58f94bc461/layer.tar
  -  /tmp/docker-squash892084052/4ee9ed2c23ba151d0fc14e9c6934e80329f2381589c6f252c1353afbd17175cf/layer.tar
  -  /tmp/docker-squash892084052/51118385cdd6ee1cbb36675b7057c49aa73cb74c1ff53350f3ad338319f514a5/layer.tar
  -  /tmp/docker-squash892084052/6a79bf36f57324bd393870cb8e38b5b76814a079f04d31327c131959d17bcbb1/layer.tar
  -  /tmp/docker-squash892084052/7f44a99d77a4e24bcb93fcfad4dfbd8f976346dd29959879092fe457dbb828b6/layer.tar
  -  /tmp/docker-squash892084052/c143be65023232019ba42cbe4d468f70fd31cf0be60fea6899dd053a9bf13655/layer.tar
  -  /tmp/docker-squash892084052/f424b38d6ca500f9d54f8b85ed50f3b8a181837ecff1c89b61097691682c1f56/layer.tar
  -  /tmp/docker-squash892084052/447f5c7d2c02da82d89b055aef28befd4c93d3095b1550c1c6cbc4ab7fe30449/layer.tar
  -  /tmp/docker-squash892084052/4c2c53673b540e07b7fd36a452f3fddb39b5e9ce6dd0f4157fffa9c1458b1001/layer.tar
  -  /tmp/docker-squash892084052/54f2bf6090b0761e86918920cce44859c8731fafcc715cb724a020dfea372ead/layer.tar
Inserted new layer d01f65ec2eb9 after b4aaa2a9b1c8
  -  b4aaa2a9b1c8
  -> d01f65ec2eb9 /bin/sh -c #(squash) from b4aaa2a9b1c8
  -  a3c77c9bff4b
  -  870d3f402f75
  -  6a79bf36f573
  -  b40fae1c3282
  -  5f0a9548e362
  -  c143be650232
  -  0717c411df0c
  -  5a22554e2f56
  -  09857f32078e
  -  7b282b939ce9
  -  54f2bf6090b0
  -  7982da6edf5b
  -  4ee9ed2c23ba
  -  447f5c7d2c02
  -  66a8e762bd6f
  -  4c2c53673b54
  -  51118385cdd6
  -  f424b38d6ca5
  -  b2b5c564bc38
  -  562e427f3c17
  -  648f99dd0ed7
  -  7f44a99d77a4
  -  cd2ccadceb07
  -  02967406f25d /bin/zsh
Squashing from d01f65ec2eb9 into d01f65ec2eb9
  -  Deleting whiteouts for layer a3c77c9bff4b
  -  Deleting whiteouts for layer 870d3f402f75
  -  Deleting whiteouts for layer 6a79bf36f573
  -  Deleting whiteouts for layer b40fae1c3282
  -  Deleting whiteouts for layer 5f0a9548e362
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x228e1b4b94c2 pc=0x2ca9e]

runtime stack:
runtime.throw(0x22f780, 0x2a)
	/usr/local/go/src/runtime/panic.go:527 +0x90
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.(*gcWork).tryGet(0xc82001c720, 0x506540)
	/usr/local/go/src/runtime/mgcwork.go:114 +0x5e
runtime.gcDrainN(0xc82001c720, 0xaef)
	/usr/local/go/src/runtime/mgcmark.go:775 +0x6b
runtime.gcAssistAlloc.func1()
	/usr/local/go/src/runtime/mgcmark.go:232 +0x172
runtime.systemstack(0xc82001b500)
	/usr/local/go/src/runtime/asm_amd64.s:262 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc1.go:674

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc82033ef98 sp=0xc82033ef90
runtime.gcAssistAlloc(0xa0, 0x1)
	/usr/local/go/src/runtime/mgcmark.go:272 +0x1f8 fp=0xc82033eff8 sp=0xc82033ef98
runtime.mallocgc(0xa0, 0x170a60, 0xc800000001, 0x7b)
	/usr/local/go/src/runtime/malloc.go:711 +0x535 fp=0xc82033f0c8 sp=0xc82033eff8
runtime.newarray(0x170a60, 0x96, 0xeafc)
	/usr/local/go/src/runtime/malloc.go:777 +0xc9 fp=0xc82033f108 sp=0xc82033f0c8
runtime.makeslice(0x168060, 0x96, 0x96, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/slice.go:32 +0x165 fp=0xc82033f158 sp=0xc82033f108
strings.Join(0xc82033f420, 0x2, 0x2, 0x1f0be8, 0x1, 0x0, 0x0)
	/usr/local/go/src/strings/strings.go:400 +0xee fp=0xc82033f250 sp=0xc82033f158
path/filepath.join(0xc82033f420, 0x2, 0x2, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path_unix.go:42 +0xfa fp=0xc82033f2e0 sp=0xc82033f250
path/filepath.Join(0xc82033f420, 0x2, 0x2, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:206 +0x41 fp=0xc82033f310 sp=0xc82033f2e0
path/filepath.walk(0xc8204803f0, 0x70, 0x5014f0, 0xc82044f860, 0x245f28, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:367 +0x37a fp=0xc82033f448 sp=0xc82033f310
path/filepath.walk(0xc820480230, 0x6a, 0x5014f0, 0xc82044f810, 0x245f28, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:374 +0x4fc fp=0xc82033f580 sp=0xc82033f448
path/filepath.walk(0xc8203fbdc0, 0x66, 0x5014f0, 0xc8203e3180, 0x245f28, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:374 +0x4fc fp=0xc82033f6b8 sp=0xc82033f580
path/filepath.walk(0xc8203896c0, 0x62, 0x5014f0, 0xc8203e2f50, 0x245f28, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:374 +0x4fc fp=0xc82033f7f0 sp=0xc82033f6b8
path/filepath.Walk(0xc8203896c0, 0x62, 0x245f28, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:396 +0xe1 fp=0xc82033f858 sp=0xc82033f7f0
main.(*Export).deleteWhiteouts(0xc8200144a0, 0xc8203896c0, 0x62, 0x0, 0x0)
	/Users/jason/go/src/github.com/jwilder/docker-squash/export.go:654 +0x43 fp=0xc82033f888 sp=0xc82033f858
main.(*Export).SquashLayers(0xc8200144a0, 0xc8203696e0, 0xc8203696e0, 0x0, 0x0)
	/Users/jason/go/src/github.com/jwilder/docker-squash/export.go:507 +0xa6e fp=0xc82033faa0 sp=0xc82033f888
main.main()
	/Users/jason/go/src/github.com/jwilder/docker-squash/main.go:160 +0x122c fp=0xc82033ff40 sp=0xc82033faa0
runtime.main()
	/usr/local/go/src/runtime/proc.go:111 +0x2b0 fp=0xc82033ff90 sp=0xc82033ff40
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82033ff98 sp=0xc82033ff90

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 6 [select, locked to thread]:
runtime.gopark(0x246300, 0xc82002c728, 0x1f36a8, 0x6, 0x39518, 0x2)
	/usr/local/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc82002c728, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc82002c728)
	/usr/local/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:227 +0x323
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 7 [chan receive]:
main.shutdown(0xc820014460, 0x1b)
	/Users/jason/go/src/github.com/jwilder/docker-squash/main.go:22 +0x7d
created by main.main
	/Users/jason/go/src/github.com/jwilder/docker-squash/main.go:73 +0x813
```

**Comment by zot** [comment]
This works for me without using docker-squash:

1. Make a container that changes the image as in the normal docker-squash instructions
2. use `docker export CONTAINER-ID | docker import - REPOSITORY:TAG` to produce the squashed image

As far as I can tell, this produces an image similar to what docker-squash would produce.

**Comment by ximencx** [comment]
@zot  but use import will run error that not have command.  so where is from the command

**Comment by zot** [comment]
@ximencx I couldn't quite understand that.

Are you talking about how `docker import` doesn't preserve the CMD? I'm not sure how to do that. The only way I know of would be to base an image off the squashed image which, I think, would make a new image layer for that.

**Comment by ximencx** [comment]
@zot yes. i mean that. but i search issue that  the project is supported old docker version.  
and use  other github project that project name is same author not same to  solve it.   
the project can amb many layer to one  and  remain command.
finally  thank you you reply

**Comment by zot** [comment]
@ximencx what exactly are you trying to do? Please be specific and give me example commands.

**Comment by ximencx** [comment]
@zot i use this project,,the url is [https://github.com/goldmann/docker-squash(https://github.com/goldmann/docker-squash)

**Comment by zot** [comment]
@ximencx if you want to export an image, just use `docker container create IMAGE --name CONTAINERNAME` to make a temporary container for IMAGE, use the export/import technique above, and add in --command options to include the commands you want. Then use remove the temporary container.

**Comment by nakulpathak3** [comment]
```
atal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0xb01dfacedebac1e pc=0x2c9d9]

runtime stack:
runtime.throw(0x22f780, 0x2a)
	/usr/local/go/src/runtime/panic.go:527 +0x90
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.(*gcWork).put(0xc820019220, 0xc8204a2360)
	/usr/local/go/src/runtime/mgcwork.go:87 +0x49
runtime.greyobject(0xc8204a2360, 0x0, 0x0, 0xc81ffdaee4, 0x0, 0x5054a0, 0xc820019220)
	/usr/local/go/src/runtime/mgcmark.go:956 +0x2f1
runtime.shade(0xc8204a2360)
	/usr/local/go/src/runtime/mgcmark.go:894 +0x9a
runtime.gcmarkwb_m(0xc820030d58, 0xc8204a2360)
	/usr/local/go/src/runtime/mbarrier.go:91 +0xc1
runtime.writebarrierptr_nostore1.func1()
	/usr/local/go/src/runtime/mbarrier.go:117 +0x134
runtime.systemstack(0xc820018000)
	/usr/local/go/src/runtime/asm_amd64.s:262 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc1.go:674

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc820378eb8 sp=0xc820378eb0
runtime.writebarrierptr_nostore1(0xc820030d58, 0xc8204a2360)
	/usr/local/go/src/runtime/mbarrier.go:118 +0x71 fp=0xc820378ef0 sp=0xc820378eb8
runtime.writebarrierptr(0xc820030d58, 0xc8204a2360)
	/usr/local/go/src/runtime/mbarrier.go:137 +0x4b fp=0xc820378f20 sp=0xc820378ef0
os.NewFile(0x20, 0xc8204f0900, 0x8f, 0x0)
	/usr/local/go/src/os/file_unix.go:54 +0x11c fp=0xc820378f78 sp=0xc820378f20
os.OpenFile(0xc8204f0900, 0x8f, 0x0, 0xffffffff00000000, 0xc8204f0900, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:109 +0x2ba fp=0xc820378ff0 sp=0xc820378f78
os.Open(0xc8204f0900, 0x8f, 0x34d000, 0x0, 0x0)
	/usr/local/go/src/os/file.go:246 +0x48 fp=0xc820379030 sp=0xc820378ff0
path/filepath.readDirNames(0xc8204f0900, 0x8f, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:402 +0x5b fp=0xc8203790a0 sp=0xc820379030
path/filepath.walk(0xc8204f0900, 0x8f, 0x5014b8, 0xc8204a6b90, 0x245f28, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:361 +0x1a2 fp=0xc8203791d8 sp=0xc8203790a0
path/filepath.walk(0xc820496380, 0x79, 0x5014b8, 0xc820479b80, 0x245f28, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:374 +0x4fc fp=0xc820379310 sp=0xc8203791d8
path/filepath.walk(0xc82047fd80, 0x72, 0x5014b8, 0xc820479860, 0x245f28, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:374 +0x4fc fp=0xc820379448 sp=0xc820379310
path/filepath.walk(0xc820471d50, 0x6a, 0x5014b8, 0xc820479270, 0x245f28, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:374 +0x4fc fp=0xc820379580 sp=0xc820379448
path/filepath.walk(0xc82040df10, 0x66, 0x5014b8, 0xc820434f00, 0x245f28, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:374 +0x4fc fp=0xc8203796b8 sp=0xc820379580
path/filepath.walk(0xc8203e0230, 0x62, 0x5014b8, 0xc8203f40f0, 0x245f28, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:374 +0x4fc fp=0xc8203797f0 sp=0xc8203796b8
path/filepath.Walk(0xc8203e0230, 0x62, 0x245f28, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:396 +0xe1 fp=0xc820379858 sp=0xc8203797f0
main.(*Export).deleteWhiteouts(0xc82000e4c0, 0xc8203e0230, 0x62, 0x0, 0x0)
	/Users/jason/go/src/github.com/jwilder/docker-squash/export.go:654 +0x43 fp=0xc820379888 sp=0xc820379858
main.(*Export).SquashLayers(0xc82000e4c0, 0xc820395620, 0xc820395620, 0x0, 0x0)
	/Users/jason/go/src/github.com/jwilder/docker-squash/export.go:507 +0xa6e fp=0xc820379aa0 sp=0xc820379888
main.main()
	/Users/jason/go/src/github.com/jwilder/docker-squash/main.go:160 +0x122c fp=0xc820379f40 sp=0xc820379aa0
runtime.main()
	/usr/local/go/src/runtime/proc.go:111 +0x2b0 fp=0xc820379f90 sp=0xc820379f40
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc820379f98 sp=0xc820379f90

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 6 [select, locked to thread]:
runtime.gopark(0x246300, 0xc82002e728, 0x1f36a8, 0x6, 0x39518, 0x2)
	/usr/local/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc82002e728, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc82002e728)
	/usr/local/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:227 +0x323
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 7 [chan receive]:
main.shutdown(0xc82000e480, 0x1b)
	/Users/jason/go/src/github.com/jwilder/docker-squash/main.go:22 +0x7d
created by main.main
	/Users/jason/go/src/github.com/jwilder/docker-squash/main.go:73 +0x813
```
same problem

**Comment by treadmillian** [comment]
Same issue on macOS BigSur 11.2.3

```
docker-squash -v
v0.2.0
```

```bash
$ sudo docker-squash -i image.tar -o squashed.tar
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x18775b792059 pc=0x2c9d9]

runtime stack:
runtime.throw(0x22f780, 0x2a)
        /usr/local/go/src/runtime/panic.go:527 +0x90
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.(*gcWork).put(0xc82001b220, 0xc82000e4c0)
        /usr/local/go/src/runtime/mgcwork.go:87 +0x49
runtime.greyobject(0xc82000e4c0, 0x0, 0x0, 0xc81ffff8d9, 0x0, 0x3511c0, 0xc82001b220)
        /usr/local/go/src/runtime/mgcmark.go:956 +0x2f1
runtime.shade(0xc82000e4c0)
        /usr/local/go/src/runtime/mgcmark.go:894 +0x9a
runtime.gcmarkwb_m(0xc8201d4c60, 0xc82000e4c0)
        /usr/local/go/src/runtime/mbarrier.go:91 +0xc1
runtime.writebarrierptr_nostore1.func1()
        /usr/local/go/src/runtime/mbarrier.go:117 +0x134
runtime.systemstack(0xc82001a000)
        /usr/local/go/src/runtime/asm_amd64.s:262 +0x79
runtime.mstart()
        /usr/local/go/src/runtime/proc1.go:674

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc8201d4b90 sp=0xc8201d4b88
runtime.writebarrierptr_nostore1(0xc8201d4c60, 0xc82000e4c0)
        /usr/local/go/src/runtime/mbarrier.go:118 +0x71 fp=0xc8201d4bc8 sp=0xc8201d4b90
runtime.writebarrierptr(0xc8201d4c60, 0xc82000e4c0)
        /usr/local/go/src/runtime/mbarrier.go:137 +0x4b fp=0xc8201d4bf8 sp=0xc8201d4bc8
runtime.convT2I(0x1ce980, 0x1b8c60, 0x313758, 0xc8201d4c68, 0xc82000e4c0, 0x53d4c8, 0xc82000e4c0)
        /usr/local/go/src/runtime/iface.go:165 +0x1a6 fp=0xc8201d4c30 sp=0xc8201d4bf8
sort.Strings(0xc820072080, 0x6, 0x64)
        /usr/local/go/src/sort/sort.go:275 +0x6c fp=0xc8201d4c88 sp=0xc8201d4c30
path/filepath.readDirNames(0xc8204e68f0, 0xa5, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:411 +0x161 fp=0xc8201d4cf8 sp=0xc8201d4c88
path/filepath.walk(0xc8204e68f0, 0xa5, 0x53d028, 0xc82000a5a0, 0x245f28, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:361 +0x1a2 fp=0xc8201d4e30 sp=0xc8201d4cf8
path/filepath.walk(0xc8204d5540, 0x9f, 0x53d028, 0xc8204c5130, 0x245f28, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:374 +0x4fc fp=0xc8201d4f68 sp=0xc8201d4e30
path/filepath.walk(0xc8204d4140, 0x92, 0x53d028, 0xc8204c4dc0, 0x245f28, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:374 +0x4fc fp=0xc8201d50a0 sp=0xc8201d4f68
path/filepath.walk(0xc820279200, 0x88, 0x53d028, 0xc820272640, 0x245f28, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:374 +0x4fc fp=0xc8201d51d8 sp=0xc8201d50a0
path/filepath.walk(0xc820237680, 0x7b, 0x53d028, 0xc82022dc70, 0x245f28, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:374 +0x4fc fp=0xc8201d5310 sp=0xc8201d51d8
path/filepath.walk(0xc820237480, 0x77, 0x53d028, 0xc82022dc20, 0x245f28, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:374 +0x4fc fp=0xc8201d5448 sp=0xc8201d5310
path/filepath.walk(0xc82021d500, 0x6a, 0x53d028, 0xc820205860, 0x245f28, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:374 +0x4fc fp=0xc8201d5580 sp=0xc8201d5448
path/filepath.walk(0xc82021c4d0, 0x66, 0x53d028, 0xc820205360, 0x245f28, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:374 +0x4fc fp=0xc8201d56b8 sp=0xc8201d5580
path/filepath.walk(0xc8201f2fc0, 0x62, 0x53d028, 0xc820204230, 0x245f28, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:374 +0x4fc fp=0xc8201d57f0 sp=0xc8201d56b8
path/filepath.Walk(0xc8201f2fc0, 0x62, 0x245f28, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:396 +0xe1 fp=0xc8201d5858 sp=0xc8201d57f0
main.(*Export).deleteWhiteouts(0xc82000e460, 0xc8201f2fc0, 0x62, 0x0, 0x0)
        /Users/jason/go/src/github.com/jwilder/docker-squash/export.go:654 +0x43 fp=0xc8201d5888 sp=0xc8201d5858
main.(*Export).SquashLayers(0xc82000e460, 0xc8201f06c0, 0xc8201f06c0, 0x0, 0x0)
        /Users/jason/go/src/github.com/jwilder/docker-squash/export.go:507 +0xa6e fp=0xc8201d5aa0 sp=0xc8201d5888
main.main()
        /Users/jason/go/src/github.com/jwilder/docker-squash/main.go:160 +0x122c fp=0xc8201d5f40 sp=0xc8201d5aa0
runtime.main()
        /usr/local/go/src/runtime/proc.go:111 +0x2b0 fp=0xc8201d5f90 sp=0xc8201d5f40
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc8201d5f98 sp=0xc8201d5f90

goroutine 5 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 6 [select, locked to thread]:
runtime.gopark(0x246300, 0xc820038728, 0x1f36a8, 0x6, 0x39518, 0x2)
        /usr/local/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc820038728, 0x0, 0x18)
        /usr/local/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc820038728)
        /usr/local/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
        /usr/local/go/src/runtime/signal1_unix.go:227 +0x323
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 7 [chan receive]:
main.shutdown(0xc82000e420, 0x1b)
        /Users/jason/go/src/github.com/jwilder/docker-squash/main.go:22 +0x7d
created by main.main
        /Users/jason/go/src/github.com/jwilder/docker-squash/main.go:73 +0x813
```
